#!/bin/bash
output=$(cat /etc/*-release)
if ! echo $output  | grep "Ubuntu"
then
	str="dnf"
	sudo $str install dnf-plugin-system-upgrade
else
	str="apt-get"
	sudo $str upgrade
	sudo $str update
fi
sudo $str install python2.7
sudo $str install virtualenv
virtualenv -p python2.7 venv
sudo chmod -R 770 venv
output=$(ls)
if ! echo $output | grep "venv"
then
	echo "Venv error!"
	exit 1
fi
echo "Venv is ok!"
sudo python2.7 get-pip.py
. ./venv/bin/activate
pip install -r requirements.txt
pip uninstall tensorboard
pip install tensorboard==2.0.2
git clone https://github.com/tensorflow/models.git
tar -xzvf ssd_mobilenet_v2_coco_2018_03_29.tar.gz
mkdir detection_models
cp ssd_mobilenet_v2_coco_2018_03_29/frozen_inference_graph.pb detection_models/ssd_mobilenet_v2_body.pb
rm ssd_mobilenet_v2_coco_2018_03_29.tar.gz
sudo apt-get install protobuf-compiler python-pil python-lxml python-tk
cd models/research
wget -O protobuf.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip
unzip protobuf.zip
./bin/protoc object_detection/protos/*.proto --python_out=.
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
cd ..
cd ..
#python2.7 conf/conf.py
#sudo python2 setup.py $str
