%YAML:1.0
---
mappointsFile: ".yaml.mappoints"
nMappoints: 2911
keyframesFile: ".yaml.keyframes"
nKeyframes: 52
featuresFile: ".yaml.features"
nFeatures: 51019
Options: 66
Options descriptions: [ ONLY_MAPPOINTS_FEATURES,
    FEATURES_FILE_NOT_DELIMITED ]
cameraMatrices:
   - { fx:5.3540002441406250e+02, fy:5.3920001220703125e+02,
       cx:3.2010000610351562e+02, cy:2.4760000610351562e+02 }
